version: '3.8'

services:
  bot:
    container_name: my_project_bot
    build: ./
    depends_on:
      - db
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn bot.main:bot --host 0.0.0.0 --port 8000'
    volumes:
      - ./bot:/src/bot
    restart: always

  db:
    container_name: my_project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
