version: '3.8'

services:
  bot:
    container_name: my_project_bot
    build: ./
    depends_on:
      - db
    command: ["sh", "-c", "sleep 10 && python main.py"]
    restart: always

  db:
    container_name: my_project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

